services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: heroes123
      POSTGRES_USER: heroes
      POSTGRES_DB: heroes_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heroes -d heroes_db"]
      interval: 5s
      timeout: 5s
      retries: 5
